//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC1002.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public Nullable<int> sellerID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string introduction { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public Nullable<int> unitsInStock { get; set; }
        public bool discontinued { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
